version: '3'
services:
    db:
        image: 'postgres:13'
        container_name: db
        network_mode: bridge
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: root
        volumes:
            - postgres_data:/var/lib/prisma-sample_posgres_data
volumes:
    postgres_data:
